version: 2
jobs:
  build:
    working_directory: ~/
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: colundrum/centos-builder-custom_nginx_rpms
      command: /sbin/init
    steps:
    - run: mkdir /shared
    - run: chown builder /shared
    - run: su builder -c 'cd /home/builder && /home/builder/run.sh'
